CREATE TABLE IF NOT EXISTS `live_visitors` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `visitor_uuid` char(36) NOT NULL,
  `session_id` varchar(191) DEFAULT NULL,
  `user_id` bigint unsigned DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `ip_address` varchar(64) DEFAULT NULL,
  `user_agent` text DEFAULT NULL,
  `device_type` varchar(30) DEFAULT NULL,
  `device_name` varchar(100) DEFAULT NULL,
  `platform` varchar(100) DEFAULT NULL,
  `browser` varchar(100) DEFAULT NULL,
  `country_code` varchar(10) DEFAULT NULL,
  `country` varchar(100) DEFAULT NULL,
  `region` varchar(100) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `current_url` text DEFAULT NULL,
  `current_path` varchar(500) DEFAULT NULL,
  `current_route` varchar(191) DEFAULT NULL,
  `current_page_title` varchar(255) DEFAULT NULL,
  `current_action` varchar(255) DEFAULT NULL,
  `current_product_id` bigint unsigned DEFAULT NULL,
  `current_product_title` varchar(255) DEFAULT NULL,
  `referrer` text DEFAULT NULL,
  `first_seen_at` timestamp NULL DEFAULT NULL,
  `last_seen_at` timestamp NULL DEFAULT NULL,
  `last_activity_at` timestamp NULL DEFAULT NULL,
  `page_views` int unsigned NOT NULL DEFAULT 0,
  `cart_items_count` int unsigned NOT NULL DEFAULT 0,
  `cart_total` decimal(18,2) NOT NULL DEFAULT 0.00,
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `live_visitors_visitor_uuid_unique` (`visitor_uuid`),
  KEY `live_visitors_last_activity_at_index` (`last_activity_at`),
  KEY `live_visitors_user_id_index` (`user_id`),
  KEY `live_visitors_device_type_index` (`device_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `live_visitor_events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `live_visitor_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned DEFAULT NULL,
  `event_type` varchar(50) NOT NULL DEFAULT 'page_view',
  `event_name` varchar(191) DEFAULT NULL,
  `page_url` text DEFAULT NULL,
  `page_path` varchar(500) DEFAULT NULL,
  `route_name` varchar(191) DEFAULT NULL,
  `page_title` varchar(255) DEFAULT NULL,
  `product_id` bigint unsigned DEFAULT NULL,
  `product_title` varchar(255) DEFAULT NULL,
  `search_query` varchar(255) DEFAULT NULL,
  `payload` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`payload`)),
  `occurred_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `live_visitor_events_live_visitor_id_index` (`live_visitor_id`),
  KEY `live_visitor_events_occurred_at_index` (`occurred_at`),
  CONSTRAINT `live_visitor_events_live_visitor_id_foreign`
    FOREIGN KEY (`live_visitor_id`) REFERENCES `live_visitors` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
